apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "authenticator.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "authenticator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "authenticator.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - containerPort: 5000
          env:
            - name: BACKEND_HOST
              value: backend-cluster-ip-service
            - name: BACKEND_PORT
              value: '3000'
            - name: OKTA_CLIENTID
              value: 0oa6jw73iiZlcYvor357
            - name: OKTA_ISSUER
              value: https://dev-556018.okta.com/oauth2/default
