apiVersion: v1
kind: Service
metadata:
  name: authenticator-cluster-ip-service
  labels:
    {{- include "authenticator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    component: authenticator-server
