apiVersion: v1
kind: Service
metadata:
  name: {{ include "authenticator.fullname" . }}
  labels:
    {{- include "authenticator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    {{- include "authenticator.selectorLabels" . | nindent 4 }}
